#!/bin/bash

SCRIPT_NAME=$0

usage() {
    cat <<EOF
Usage: ${SCRIPT_NAME} [options...]
  options:
    -l ... enable live reload
    -t ... enable test
EOF
}

LIVE_RELOAD_ENABLED=0
TEST_ENABLED=0

while getopts hlt OPTION
do
    case ${OPTION} in
        l)
            echo 'enabled [live reload option]'
            LIVE_RELOAD_ENABLED=1
            ;;
        t)
            echo 'enabled [test option]'
            TEST_ENABLED=1
            ;;
        h)
            usage
            exit 0
            ;;
        \?)
           usage
           exit 1
           ;;
    esac
done

npm init -y
npm i -D typescript
npm i -D prettier

SCRIPTS=''

SCRIPTS="${SCRIPTS}"'    "build": "tsc --project ."'
SCRIPTS="${SCRIPTS}"',\n'
SCRIPTS="${SCRIPTS}"'    "build:watch": "tsc --project . --watch"'

if [ ${TEST_ENABLED} -eq 1 ]; then
    SCRIPTS="${SCRIPTS}"',\n'
    SCRIPTS="${SCRIPTS}"'    "typecheck": "tsc --project ./tsconfig.typecheck.json"'
    SCRIPTS="${SCRIPTS}"',\n'
    SCRIPTS="${SCRIPTS}"'    "typecheck:watch": "tsc --project ./tsconfig.typecheck.json --watch"'
fi

if [ ${TEST_ENABLED} -eq 1 ]; then
    SCRIPTS="${SCRIPTS}"',\n'
    SCRIPTS="${SCRIPTS}"'    "test": "jest"'
fi

if [ ${TEST_ENABLED} -eq 1 ]; then
    SCRIPTS="${SCRIPTS}"',\n'
    SCRIPTS="${SCRIPTS}"'    "format": "prettier --write src test"'
else
    SCRIPTS="${SCRIPTS}"',\n'
    SCRIPTS="${SCRIPTS}"'    "format": "prettier --write src"'
fi

if [ ${TEST_ENABLED} -eq 1 ]; then
    SCRIPTS="${SCRIPTS}"',\n'
    SCRIPTS="${SCRIPTS}"'    "test": "jest"'
fi

perl -wp -i -e 's!    "test": .+!'"${SCRIPTS}"'!' package.json

echo '{
  "compilerOptions": {
    "target": "esnext",
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "lib": ["esnext"],
    "baseUrl": "./src",
    "outDir": "dist",
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "skipLibCheck": true,
    "esModuleInterop": true
  },
  "include": [
    "src"
  ]
}' > tsconfig.json

if [ ${TEST_ENABLED} -eq 1 ]; then
    echo '{
  "extends": "./tsconfig",
  "compilerOptions": {
    "baseUrl": "./",
    "noEmit": true
  },
  "include": [
    "src", "test"
  ]
}' > tsconfig.typecheck.json
fi

echo '{
  "singleQuote": true,
  "printWidth": 120
}' > .prettierrc.json

if [ ${LIVE_RELOAD_ENABLED} -eq 1 ]; then
    npm i -D nodemon ts-node
fi

if [ ${TEST_ENABLED} -eq 1 ]; then
    npm i -D jest @types/jest
    npm i -D esbuild esbuild-jest

    echo 'module.exports = {
  testEnvironment: '"'"'node'"'"',
  transform: {
    "^.+\\.tsx?$": "esbuild-jest"
  }
};' > jest.config.js
fi

mkdir src

if [ ${TEST_ENABLED} -eq 1 ]; then
    mkdir test
fi

echo '
### versions
'

echo 'typescript:'
npx tsc --version

echo

echo 'prettier:'
npx prettier --version


if [ ${LIVE_RELOAD_ENABLED} -eq 1 ]; then
    echo

    echo 'nodemon:'
    npx nodemon --version

    echo

    echo 'ts-node:'
    npx ts-node --version
fi

if [ ${TEST_ENABLED} -eq 1 ]; then
    echo

    echo 'jest:'
    npx jest --version
fi

echo '
### executed commands.

$ npm init -y
$ npm i -D typescript
$ npm i -D prettier'

if [ ${LIVE_RELOAD_ENABLED} -eq 1 ]; then
    echo '$ npm i -D nodemon ts-node'
fi

if [ ${TEST_ENABLED} -eq 1 ]; then
    echo '$ npm i -D jest @types/jest
$ npm i -D esbuild esbuild-jest'
fi

if [ ${TEST_ENABLED} -eq 1 ]; then
    echo '$ mkdir src test'
else
    echo '$ mkdir src'
fi
