#!/bin/bash

echo 'current TFLint version'
tflint --version

echo

echo 'downloading...'

curl -sL "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o $HOME/.local/bin/tflint.zip \
    && cd $HOME/.local/bin \
    && unzip -o tflint.zip \
    && rm tflint.zip

chmod a+x $HOME/.local/bin/tflint

echo

echo 'latest TFLint version'
tflint --version
