#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)

${SCRIPT_DIR}/install-basic-packages

sudo apt install -y language-pack-ja
sudo update-locale LANG=ja_JP.UTF-8
sudo timedatectl set-timezone Asia/Tokyo
sudo apt install -y manpages-ja manpages-ja-dev
echo 'Acquire::Language "ja_JP";' | sudo tee /etc/apt/apt.conf.d/99translations > /dev/null
sudo apt update
