#!/bin/bash

TERRAGRUNT_LATEST_VERSION=$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r .tag_name)

echo 'current Terragrunt version'
terragrunt -version

echo

echo "downloading Terragrunt ${TERRAGRUNT_LATEST_VERSION}..."

curl -s -L https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_LATEST_VERSION}/terragrunt_linux_amd64 -o $HOME/.local/bin/terragrunt
chmod a+x $HOME/.local/bin/terragrunt

echo

echo 'installed Terragrunt version'
terragrunt -version
