#!/bin/bash

echo 'current Docker Compose version'
docker-compose -v

echo

echo 'downloading...'
sudo curl -s -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

echo

echo 'installed Docker Compose version'
docker-compose -v
