#!/bin/bash

HADOLINT_LATEST_VERSION=$(curl -s https://api.github.com/repos/hadolint/hadolint/releases/latest | jq -r .tag_name)

echo 'current hadolint versoin'
hadolint --version

echo

echo "downloading hadolint ${HADOLINT_LATEST_VERSION}..."

curl -s -o $HOME/.local/bin/hadolint -L https://github.com/hadolint/hadolint/releases/download/${HADOLINT_LATEST_VERSION}/hadolint-Linux-x86_64
chmod a+x $HOME/.local/bin/hadolint

echo

echo 'installed hadolint version'
hadolint --version
