#!/bin/bash


PYRIGHT_DIR=~/.emacs.d/.cache/lsp/npm/pyright
rm -rf ${PYRIGHT_DIR}
npm i -g --prefix ${PYRIGHT_DIR} pyright

echo

echo 'installed pyright version'

${PYRIGHT_DIR}/bin/pyright --version

echo
