#!/bin/bash


TS_SERVER_DIR=~/.emacs.d/.cache/lsp/npm/typescript-language-server
rm -rf ${TS_SERVER_DIR}
npm i -g --prefix ${TS_SERVER_DIR} typescript-language-server typescript

echo

echo 'installed typescript-language-server version'

${TS_SERVER_DIR}/bin/typescript-language-server --version

echo

TS_DIR=~/.emacs.d/.cache/lsp/npm/typescript
rm -rf ${TSDIR}
npm i -g --prefix ${TS_DIR} typescript typescript

echo

echo 'installed typescript version'

${TS_DIR}/bin/tsc --version

echo
