#!/bin/bash

VAGRANT_VERSION=$1
curl -s -L https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb -o /tmp/vagrant_${VAGRANT_VERSION}_x86_64.deb
sudo dpkg -i /tmp/vagrant_${VAGRANT_VERSION}_x86_64.deb
rm /tmp/vagrant_${VAGRANT_VERSION}_x86_64.deb
