#!/bin/bash

HADOLINT_LATEST_VERSION=$(curl -s https://api.github.com/repos/hadolint/hadolint/releases/latest | jq -r .tag_name)

echo 'current hadolint versoin'
hadolint --version

echo

echo "downloading hadolint ${HADOLINT_LATEST_VERSION}..."

sudo curl -s -o /usr/local/bin/hadolint -L https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
sudo chmod a+x /usr/local/bin/hadolint

echo

echo 'installed hadolint version'
hadolint --version
