#!/bin/bash

## language server install functions

install-bash-language-server() {
    BASH_SERVER_DIR=~/.emacs.d/.cache/lsp/npm/bash-language-server
    rm -rf ${BASH_SERVER_DIR}
    npm i -g --prefix ${BASH_SERVER_DIR} bash-language-server

    echo

    echo 'installed bash-language-server version'

    ${BASH_SERVER_DIR}/bin/bash-language-server --version
}

install-typescript-language-server() {
    TS_SERVER_DIR=~/.emacs.d/.cache/lsp/npm/typescript-language-server
    rm -rf ${TS_SERVER_DIR}
    npm i -g --prefix ${TS_SERVER_DIR} typescript-language-server typescript

    echo

    echo 'installed typescript-language-server version'

    ${TS_SERVER_DIR}/bin/typescript-language-server --version

    echo

    TS_DIR=~/.emacs.d/.cache/lsp/npm/typescript
    rm -rf ${TSDIR}
    npm i -g --prefix ${TS_DIR} typescript typescript

    echo

    echo 'installed typescript version'

    ${TS_DIR}/bin/tsc --version

    echo
}

install-pyright() {
    PYRIGHT_DIR=~/.emacs.d/.cache/lsp/npm/pyright
    rm -rf ${PYRIGHT_DIR}
    npm i -g --prefix ${PYRIGHT_DIR} pyright

    echo

    echo 'installed pyright version'

    ${PYRIGHT_DIR}/bin/pyright --version

    echo
}

install-golsp() {
    go install golang.org/x/tools/gopls@latest

    echo 'installed gopls version'

    gopls version

    echo
}

install-copilot-lsp() {
    COPILOT_DIR=~/.emacs.d/.cache/copilot
    rm -rf ${COPILOT_DIR}
    npm i -g --prefix ${COPILOT_DIR} \@github/copilot-language-server

    echo

    echo 'installed copilot language server version'

    ${COPILOT_DIR}/bin/copilot-language-server --version

    echo
}


## execute install language servers

install-bash-language-server

install-typescript-language-server

install-pyright

install-golsp

# install-copilot-lsp
