#!/bin/bash

TERRAFORM_LATEST_VERSION=`curl -s https://www.terraform.io/downloads.html | grep linux_amd64 | perl -wp -e 's!.+".+/terraform/(.+?)/terraform.+!$1!' | head -n 1`

echo "install Terraform ${TERRAFORM_LATEST_VERSION}"

sudo curl -s -L -o /usr/local/bin/terraform_${TERRAFORM_LATEST_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_LATEST_VERSION}/terraform_${TERRAFORM_LATEST_VERSION}_linux_amd64.zip
cd /usr/local/bin
sudo unzip -o terraform_${TERRAFORM_LATEST_VERSION}_linux_amd64.zip
sudo rm /usr/local/bin/terraform_${TERRAFORM_LATEST_VERSION}_linux_amd64.zip
sudo chmod a+x /usr/local/bin/terraform
