#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)

${SCRIPT_DIR}/install-localize-ja

echo "postfix postfix/main_mailer_type select No configuration" | sudo debconf-set-selections

sudo DEBIAN_FRONTEND=noninteractive apt install -y \
  ubuntu-desktop \
  ibus-mozc \
  fcitx5-mozc \
  tmux \
  emacs \
  fonts-cascadia-code \
  xclip \
  xsel

sudo apt purge -y \
  postfix \
  mailutils

sudo apt install -y \
  language-pack-gnome-ja \
  $(check-language-support -l ja)

gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
