#!/bin/bash

DOCKER_COMPOSE_LATEST_VERSION=`curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name`

echo 'current Docker Compose version'
docker-compose -v

echo

echo "downloading Docker Compose ${DOCKER_COMPOSE_LATEST_VERSION}..."
sudo curl -s -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_LATEST_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

echo

echo 'installed Docker Compose version'
docker-compose -v
