#!/bin/bash

npm init -y
npm i -D typescript
npm i -D -E prettier

perl -wp -i -e 's!    "test": .+!    "build": "tsc",\n    "format": "prettier --write src"!' package.json

echo '{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "baseUrl": "./src",
    "outDir": "dist",
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true
  },
  "include": [
    "src"
  ]
}' > tsconfig.json

echo {} > .prettierrc.json

mkdir src

echo '
### versions
'

echo 'typescript:'
npx tsc --version

echo

echo 'prettier:'
npx prettier --version

echo

echo '### settings'

echo 'package.json:'
echo
cat package.json

echo
echo 'tsconfig.json:'
echo
cat tsconfig.json

echo '
### executed commands.

$ npm init -y
$ npm i -D typescript
$ npm i -D -E prettier
$ echo {} > .prettierrc.json
$ mkdir src
'
