#!/bin/bash

TOOLS=(
    golang.org/x/tools/gopls@latest
    github.com/motemen/gore/cmd/gore@latest
    github.com/mdempsky/gocode@latest
    github.com/go-delve/delve/cmd/dlv@latest
)

cd /tmp

for TOOL in "${TOOLS[@]}"
do
    echo "update [${TOOL}] ..."
    go install ${TOOL}
    echo
done
