#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

## Java

### sdkman
echo 'update, sdkman and candidates'

. ${HOME}/.sdkman/bin/sdkman-init.sh
sdk update && sdk upgrade

echo

## Node.js

### nvm
echo 'update, nvm and Node.js LTS'

cd ${HOME}/.nvm
git fetch --tags origin
git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
cd -

. ${HOME}/.nvm/nvm.sh

nvm install --lts

echo

## Python

### uv
echo 'update uv' 
uv self update

echo

## Rust

### rustp
echo 'update, rust toolchain and rustup self'

rustup update
rustup self update

echo

## lap-mode language servers
echo 'install language servers for lsp-mode'
${SCRIPT_DIR}/install-latest-language-servers-for-lsp-mode

echo
